project_id = "pfszkghqoxybhbaouliw"

[functions.ml-backend]
verify_jwt = false

[functions.fetch-market-data]
verify_jwt = false

[functions.alpaca-trading]
verify_jwt = false

[functions.sandbox-execute]
verify_jwt = false

[functions.brokerage-accounts]
verify_jwt = false
