project_id = "pfszkghqoxybhbaouliw"

[functions.ml-backend]
verify_jwt = false

[functions.fetch-market-data]
verify_jwt = false

[functions.alpaca-trading]
verify_jwt = false

[functions.sandbox-execute]
verify_jwt = false

[functions.brokerage-accounts]
verify_jwt = false

[functions.trading-bot]
verify_jwt = false

[functions.stock-monitor]
verify_jwt = false

[functions.run-automations]
verify_jwt = false

[functions.ai-strategy-builder]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email-token]
verify_jwt = false

[functions.instagram-marketing-bot]
verify_jwt = false
