-- Table to store signals generated by deployed models
CREATE TABLE public.model_signals (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  model_id UUID NOT NULL REFERENCES public.models(id) ON DELETE CASCADE,
  ticker TEXT NOT NULL,
  signal_type TEXT NOT NULL CHECK (signal_type IN ('BUY', 'SELL', 'HOLD')),
  confidence NUMERIC,
  price_at_signal NUMERIC,
  quantity INTEGER DEFAULT 1,
  metadata JSONB,
  generated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  executed_at TIMESTAMP WITH TIME ZONE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'executed', 'failed', 'cancelled'))
);

-- Table to track trades executed for subscribers (copy trades)
CREATE TABLE public.subscriber_trades (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  subscription_id UUID NOT NULL REFERENCES public.subscriptions(id) ON DELETE CASCADE,
  signal_id UUID NOT NULL REFERENCES public.model_signals(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id),
  ticker TEXT NOT NULL,
  side TEXT NOT NULL CHECK (side IN ('buy', 'sell')),
  quantity INTEGER NOT NULL,
  executed_price NUMERIC,
  pnl NUMERIC,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'executed', 'failed', 'cancelled')),
  alpaca_order_id TEXT,
  error_message TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  executed_at TIMESTAMP WITH TIME ZONE
);

-- Table to track deployed model bots
CREATE TABLE public.deployed_models (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  model_id UUID NOT NULL REFERENCES public.models(id) ON DELETE CASCADE UNIQUE,
  user_id UUID NOT NULL REFERENCES public.profiles(id),
  status TEXT NOT NULL DEFAULT 'stopped' CHECK (status IN ('running', 'stopped', 'error')),
  last_signal_at TIMESTAMP WITH TIME ZONE,
  total_signals INTEGER DEFAULT 0,
  total_trades INTEGER DEFAULT 0,
  config JSONB,
  error_message TEXT,
  deployed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.model_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriber_trades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deployed_models ENABLE ROW LEVEL SECURITY;

-- Model signals: Model owner can manage, subscribers can view
CREATE POLICY "Model owners can manage signals" ON public.model_signals
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.models WHERE id = model_id AND user_id = auth.uid())
  );

CREATE POLICY "Subscribers can view signals" ON public.model_signals
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.subscriptions s
      JOIN public.models m ON m.id = s.model_id
      WHERE s.model_id = model_signals.model_id
      AND s.subscriber_id = auth.uid()
      AND s.status = 'active'
    )
  );

-- Subscriber trades: Users can view their own trades
CREATE POLICY "Users can view their own subscriber trades" ON public.subscriber_trades
  FOR SELECT USING (user_id = auth.uid());

-- Deployed models: Owners can manage, public models visible to all
CREATE POLICY "Model owners can manage deployments" ON public.deployed_models
  FOR ALL USING (user_id = auth.uid());

CREATE POLICY "Active public deployments visible to all" ON public.deployed_models
  FOR SELECT USING (
    status = 'running' AND EXISTS (
      SELECT 1 FROM public.models WHERE id = model_id AND is_public = true
    )
  );

-- Enable realtime for signals and trades
ALTER PUBLICATION supabase_realtime ADD TABLE public.model_signals;
ALTER PUBLICATION supabase_realtime ADD TABLE public.subscriber_trades;

-- Trigger to update deployed_models.updated_at
CREATE TRIGGER update_deployed_models_updated_at
  BEFORE UPDATE ON public.deployed_models
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();